#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE="${PROVISIONING_ENV_FILE:-.provisioning.env}"
TOTAL_STAGES=19

branding_url_uses_domain() {
  local url="$1" domain="$2" host
  [[ "$url" == https://* ]] || return 1
  host="${url#https://}"
  host="${host%%/*}"
  [[ -n "$host" && "$host" != *":"* && "$host" != *"@"* ]] || return 1
  host="${host,,}"
  [[ "$host" == "$domain" || "$host" == *."$domain" ]]
}

banner "Agent Data Oracle production provisioning"

stage "Local prerequisites and cost boundary"
say "This prepares the private production shell. It does not activate the usage-learning phase."
step "Run terraform version and gcloud auth list. If no active Google account appears, run gcloud auth login."
warn "Creating Cloud SQL begins a running-instance charge. Use local Docker PostgreSQL for ordinary development."
step "Confirm that you own the Google Cloud billing account and GitHub repository, and control the Gmail sender account and its recovery methods."
open_url "https://console.cloud.google.com/billing"
step "Create monthly budget alerts before creating resources. Ordinary alerts warn; they do not automatically stop charges."
pause "Press Enter after you have confirmed the cost boundary."

stage "Production project and billing"
open_url "https://console.cloud.google.com/projectcreate"
step "For Project name, use Agent Data Oracle Production."
step "For Project ID, try agent-data-oracle-prod; if unavailable, use agent-data-oracle-prod-2026 or another short lowercase suffix. Copy the final ID: it cannot be changed later."
step "Choose your founder-controlled organization, or No organization if this is a personal Google Cloud account, then click Create."
step "After creation, select the new project in the top project selector. Go to Billing, choose Link a billing account, and attach your founder-owned billing account."
step "There is no region choice on this screen. Terraform creates all application resources later in Frankfurt (europe-west3)."
ask GCP_PROJECT_ID "Paste the production Google Cloud project ID:"
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
say "gcloud config set project $GCP_PROJECT_ID"
step "For Terraform credentials, run gcloud auth application-default set-quota-project $GCP_PROJECT_ID. If it says ADC is missing, run gcloud auth application-default login first using the same account."
step "The separate backup project belongs to ticket #33 and is deliberately not provisioned here."
pause "Press Enter after billing is linked to the production project."

stage "GitHub deployment approval"
open_url "https://github.com/LaverdeS/agent-data-oracle/settings/environments"
step "Create the production environment and add yourself as its required reviewer. Leave Prevent self-review off if you are the only reviewer."
step "Open Settings -> Branches (or Rulesets) and protect main. Enable Require a pull request before merging; leave required approving reviews at 0 for this solo workflow."
step "Enable Require status checks and select quality, secret-scan, and terraform. Leave Require branches to be up to date off to avoid repeat builds."
step "Enable Require conversation resolution. Leave signed commits, linear history, merge queue, and deployment-before-merge off for now."
step "Do not allow force pushes or branch deletion. Keep the admin bypass only for emergency recovery."
step "Do not add Google service-account keys or production secrets to GitHub."
pause "Press Enter after the production environment is protected."

stage "Choose the OAuth branding domain"
say "The application remains on its generated run.app address. This domain is used only for Google's public OAuth branding pages; it does not require Workspace or a custom application load balancer."
ask OAUTH_BRANDING_DOMAIN "Paste the bare domain you propose using, without https:// or a path (for example, example.com):"
OAUTH_BRANDING_DOMAIN="${OAUTH_BRANDING_DOMAIN,,}"
if [[ ! "$OAUTH_BRANDING_DOMAIN" =~ ^([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,63}$ ]]; then
  warn "The branding domain must be a non-empty bare domain such as example.com. Nothing was changed in Google Auth Platform."
  exit 1
fi
warn "Registering a new domain creates a paid renewable commitment. Record its price, registrar, renewal owner, and recovery method for #35."
if ! confirm "Do you approve using or registering $OAUTH_BRANDING_DOMAIN and accept its renewal responsibility"; then
  warn "Provisioning stopped before any domain purchase or OAuth configuration."
  exit 1
fi
step "If you do not already own the domain, register it now through the founder-controlled registrar account. Enable renewal and secure the registrar account and recovery method."
if ! confirm "Do you now control $OAUTH_BRANDING_DOMAIN in the founder registrar account"; then
  warn "Provisioning stopped before public-page or OAuth configuration. Finish domain registration, then rerun the wizard."
  exit 1
fi
write_env OAUTH_BRANDING_DOMAIN "$OAUTH_BRANDING_DOMAIN"

stage "Publish the OAuth branding pages"
step "Publish a public HTTPS homepage that names Agent Data Oracle, describes its evidence-queue and sign-in-email functions, and links to its privacy policy and terms. The pages must not require sign-in."
step "The privacy page must accurately disclose how Google user data is accessed, used, stored, shared, retained, and deleted. State that the sender's authorization is used solely to send sign-in links with gmail.send, cannot read the mailbox, is stored in Google Secret Manager, and follows Google's Limited Use requirements."
ask OAUTH_APP_HOME_URL "Paste the public OAuth application homepage URL:"
ask OAUTH_PRIVACY_POLICY_URL "Paste the public privacy-policy URL:"
ask OAUTH_TERMS_URL "Paste the public terms-of-service URL:"
if ! branding_url_uses_domain "$OAUTH_APP_HOME_URL" "$OAUTH_BRANDING_DOMAIN" ||
   ! branding_url_uses_domain "$OAUTH_PRIVACY_POLICY_URL" "$OAUTH_BRANDING_DOMAIN" ||
   ! branding_url_uses_domain "$OAUTH_TERMS_URL" "$OAUTH_BRANDING_DOMAIN"; then
  warn "All three URLs must use HTTPS and the verified domain or one of its subdomains. Nothing was changed in Google Auth Platform."
  exit 1
fi
write_env OAUTH_APP_HOME_URL "$OAUTH_APP_HOME_URL"
write_env OAUTH_PRIVACY_POLICY_URL "$OAUTH_PRIVACY_POLICY_URL"
write_env OAUTH_TERMS_URL "$OAUTH_TERMS_URL"
if ! confirm "Are all three pages public, final enough to show the sender, and linked from the homepage"; then
  warn "Provisioning stopped before Google Auth Platform configuration. Publish or correct the pages, then rerun the wizard."
  exit 1
fi

stage "Verify the OAuth branding domain"
open_url "https://search.google.com/search-console/welcome"
step "While signed in as a production-project owner or editor, add the domain as a Domain property and complete Google's DNS TXT-record ownership check."
step "Open each saved URL in a signed-out browser window and confirm it loads over HTTPS. Confirm the homepage links to the same privacy and terms URLs."
if ! confirm "Does Search Console show domain ownership verified and do all three signed-out page checks pass"; then
  warn "Provisioning stopped before OAuth configuration. Finish domain verification or repair the pages, then rerun the wizard."
  exit 1
fi

stage "Secure the consumer Gmail sender"
say "Use consumer Gmail with only gmail.send. The OAuth branding domain does not host the application and does not create a Workspace subscription."
step "Prefer a new free Gmail account used only for Agent Data Oracle sign-in mail. Reusing your existing Gmail account is allowed, but it exposes that address and combines its security and availability with production access."
ask GMAIL_SENDER_ACCOUNT "Paste the founder-controlled consumer Gmail sender address (never paste its password):"
write_env GMAIL_SENDER_ACCOUNT "$GMAIL_SENDER_ACCOUNT"
if confirm "Is this also the Google account that owns the production project"; then
  warn "You are accepting a larger blast radius: compromise, suspension, or recovery trouble can affect both GCP control and sign-in delivery."
  write_env GMAIL_SENDER_ACCOUNT_MODE "reused-founder-account-risk-accepted"
else
  write_env GMAIL_SENDER_ACCOUNT_MODE "separate-free-sender"
fi
open_url "https://myaccount.google.com/security"
step "While signed in as the sender, enable two-step verification and verify its recovery email and phone. Store recovery material in the founder's password manager."
if ! confirm "Are sender two-step verification and recovery controls complete"; then
  warn "Provisioning stopped before Google Auth Platform configuration. Secure the sender, then rerun the wizard."
  exit 1
fi

stage "Configure and publish OAuth branding"
open_url "https://console.cloud.google.com/apis/library/gmail.googleapis.com?project=$GCP_PROJECT_ID"
step "Enable the Gmail API in the production project."
open_url "https://console.cloud.google.com/auth/branding?project=$GCP_PROJECT_ID"
step "Under Branding, use Agent Data Oracle as the app name, select a monitored founder address as User support email, and keep the founder in Developer contact information. Do not upload a logo for this bounded phase."
step "Remove stale or additional Authorized domains, then add $OAUTH_BRANDING_DOMAIN so it is the only entry. Set Application home page to $OAUTH_APP_HOME_URL, Privacy policy to $OAUTH_PRIVACY_POLICY_URL, and Terms of Service to $OAUTH_TERMS_URL, then save."
step "Click Verify Branding. Fix any reported domain or page issue; do not use placeholder URLs. When the status becomes Ready to publish, click Publish branding within seven days."
if ! confirm "Does Google Auth Platform show the branding as published with exactly the saved domain and URLs"; then
  warn "Provisioning stopped before audience publication or OAuth client creation. Finish branding verification and publication, then rerun the wizard."
  exit 1
fi

stage "Publish the OAuth audience and data access"
open_url "https://console.cloud.google.com/auth/audience?project=$GCP_PROJECT_ID"
step "Set Audience to External. Do not add application users as OAuth users; only the sender authorizes Gmail access."
open_url "https://console.cloud.google.com/auth/dataaccess?project=$GCP_PROJECT_ID"
step "Add only https://www.googleapis.com/auth/gmail.send. It is a sensitive scope, not a restricted scope, and cannot read the mailbox."
open_url "https://console.cloud.google.com/auth/audience?project=$GCP_PROJECT_ID"
step "Click Publish app and confirm the publishing status is In production before the final token is issued."
warn "This sender-only personal-use app may remain unverified and show the sender a warning. Recheck Google's current personal-use exemption and quota terms before authorizing. Do not continue in Testing: a Gmail-scoped refresh token issued there expires after seven days."
if ! confirm "Does Audience show In production and does Data Access contain only gmail.send"; then
  warn "Provisioning stopped before OAuth client creation. Correct audience or scope configuration, then rerun the wizard."
  exit 1
fi

stage "Create the OAuth web client"
open_url "https://console.cloud.google.com/auth/clients?project=$GCP_PROJECT_ID"
step "Under Clients, create a Web application OAuth client. Add https://developers.google.com/oauthplayground as an authorized redirect URI. Save its client ID and secret temporarily in the founder's password manager, never in this wizard or GitHub."
pause "Press Enter after the OAuth web client is saved and its credentials are in the founder's password manager."

stage "Create Frankfurt infrastructure"
step "Install Terraform and gcloud, authenticate as the founder, and run from the repository root:"
say "terraform -chdir=infra/terraform init"
say "terraform -chdir=infra/terraform apply -var project_id=$GCP_PROJECT_ID -var github_repository=LaverdeS/agent-data-oracle"
warn "Approve only a plan that creates the intended europe-west3 resources. This creates the Cloud SQL instance."
pause "Press Enter only after the first Terraform apply completes successfully."

stage "Record non-secret Terraform outputs"
step "Run terraform -chdir=infra/terraform output and copy these non-secret values."
ask CLOUD_SQL_CONNECTION_NAME "Paste cloud_sql_connection_name:"
ask WORKLOAD_IDENTITY_PROVIDER "Paste workload_identity_provider:"
ask DEPLOYER_SERVICE_ACCOUNT "Paste deployer_service_account:"
ask CLOUD_SQL_INSTANCE "Paste the Cloud SQL instance name (normally agent-data-oracle-postgres):"
write_env CLOUD_SQL_CONNECTION_NAME "$CLOUD_SQL_CONNECTION_NAME"
write_env WORKLOAD_IDENTITY_PROVIDER "$WORKLOAD_IDENTITY_PROVIDER"
write_env DEPLOYER_SERVICE_ACCOUNT "$DEPLOYER_SERVICE_ACCOUNT"
write_env CLOUD_SQL_INSTANCE "$CLOUD_SQL_INSTANCE"

stage "Authorize the consumer Gmail sender"
open_url "https://developers.google.com/oauthplayground/"
step "Open the Playground settings, enable Use your own OAuth credentials, choose Offline access and Force prompt: Consent, then enter the web-client ID and secret from your password manager."
step "Enter only https://www.googleapis.com/auth/gmail.send, choose Authorize APIs, and select $GMAIL_SENDER_ACCOUNT. If warned that the app is unverified, verify the project name and exact scope before continuing."
step "Exchange the authorization code for tokens. Copy the refresh token; do not paste it into this wizard, shell history, screenshots, or an issue."
open_url "https://console.cloud.google.com/security/secret-manager?project=$GCP_PROJECT_ID"
step "Add the client ID, client secret, and refresh token directly as versions of gmail-oauth-client-id, gmail-oauth-client-secret, and gmail-oauth-refresh-token."
warn "Only the sender grants OAuth. A final token created in Testing will expire after seven days; confirm the app says In production before continuing."
pause "Press Enter after the three Gmail OAuth secret versions exist in regional Secret Manager."

stage "Database login and remaining secrets"
open_url "https://console.cloud.google.com/security/secret-manager?project=$GCP_PROJECT_ID"
step "Create the least-privilege PostgreSQL login and schema access. Keep its password out of Terraform and GitHub."
step "Enter these directly into regional Secret Manager: database-url, auth-secret, and founder-emails. Confirm the three Gmail OAuth secret versions from the previous stage are also present."
step "Use the Cloud SQL Unix-socket database URL in docs/provision-gcp.md."
warn "This wizard deliberately never stores, displays, or uploads runtime secrets."
pause "Press Enter after each required Secret Manager version has been added."

stage "Bootstrap the Cloud Run service"
step "Build and push the first digest-pinned image to Artifact Registry using an authenticated founder session."
ask BOOTSTRAP_IMAGE "Paste its digest-pinned image reference:"
write_env BOOTSTRAP_IMAGE "$BOOTSTRAP_IMAGE"
say "terraform -chdir=infra/terraform apply -var project_id=$GCP_PROJECT_ID -var github_repository=LaverdeS/agent-data-oracle -var create_application=true -var bootstrap_image=$BOOTSTRAP_IMAGE"
step "Copy service_url, then apply once more with -var public_origin=https://THE-GENERATED.run.app."
ask SERVICE_URL "Paste the generated https://…run.app service URL:"
write_env SERVICE_URL "$SERVICE_URL"
pause "Press Enter after the service and migration job exist with the generated run.app origin."

stage "Connect GitHub Actions through federation"
step "The following values are non-secret production variables."
if confirm "Set them in the current GitHub repository using gh now"; then
  set_var GCP_PROJECT_ID "$GCP_PROJECT_ID"
  set_var GCP_WORKLOAD_IDENTITY_PROVIDER "$WORKLOAD_IDENTITY_PROVIDER"
  set_var GCP_DEPLOYER_SERVICE_ACCOUNT "$DEPLOYER_SERVICE_ACCOUNT"
else
  SKIPPED+=("GitHub production variables: GCP_PROJECT_ID, GCP_WORKLOAD_IDENTITY_PROVIDER, GCP_DEPLOYER_SERVICE_ACCOUNT")
fi

stage "Deploy and smoke-test the private shell"
open_url "https://github.com/LaverdeS/agent-data-oracle/actions/workflows/deploy.yml"
step "Run the manual production deployment with an immutable image tag, then approve it as founder."
say "scripts/smoke-deployed-shell.sh $SERVICE_URL"
step "Send a sign-in request only to a founder-controlled inbox and complete the link flow."
pause "Press Enter after health, generic sign-in, and authenticated-shell checks succeed."

stage "Controlled Gmail failure and recovery"
warn "This deliberately creates a broken email-delivery revision. Do it only in a non-public test window."
step "Follow the invalid-refresh-token drill and immediate recovery steps in docs/provision-gcp.md."
step "Verify the generic response and redacted sign_in_delivery_failed log event; restore a valid secret version immediately."
pause "Press Enter after the recovered revision is serving and the failure evidence is recorded."

stage "Park or go live"
say "For a working public site, leave Cloud SQL running. For a cost-controlled pause, stop it after testing."
say "gcloud sql instances patch $CLOUD_SQL_INSTANCE --project $GCP_PROJECT_ID --activation-policy=NEVER"
step "While stopped, the public URL may resolve but the application cannot use its database; storage and IP charges still apply."
say "To resume: gcloud sql instances patch $CLOUD_SQL_INSTANCE --project $GCP_PROJECT_ID --activation-policy=ALWAYS"
warn "Do not advertise the site as usable while the database is parked, and do not activate the usage-learning phase here."
pause "Press Enter after choosing the appropriate running or parked state."

# ── Example stage: replace with your real steps ───────────────────────────
# ──────────────────────────────────────────────────────────────────────────

finish
